apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 32000
  type: LoadBalancer